# For more info on HTTP files go to https://aka.ms/vs/httpfile
@hostname=localhost
@port=57679

// List all persons
GET http://{{hostname}}:{{port}}/Persons

###

// Get a specific persons
@id_to_get=8
GET http://{{hostname}}:{{port}}/Persons/{{id_to_get}}

###

// Add a new persons
POST http://{{hostname}}:{{port}}/Persons
Content-Type: application/json

{
  "name": "John Doe 2",
  "email": "test@test.com",
  "phoneNumber": "1234567890"
}

###

// Update a persons
@id_to_update=1
PUT http://{{hostname}}:{{port}}/Persons/{{id_to_update}}
Content-Type: application/json

{
  "id": {{id_to_update}},
  "name": "ardalis2"
}

###

// Delete a person
@id_to_delete=1
DELETE http://{{hostname}}:{{port}}/Persons/{{id_to_delete}}

###

// Delete a person
@id_to_search=1
DELETE http://{{hostname}}:{{port}}/NewMS/{{id_to_search}}

